# Generated by Django 6.0.7 on 2026-07-13 20:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalogo", "0001_initial"),
        ("equipos", "0001_initial"),
        ("paquetes", "0001_initial"),
        ("solicitudes", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Reserva",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        blank=True, max_length=20, unique=True, verbose_name="código"
                    ),
                ),
                ("personas", models.PositiveIntegerField()),
                ("contactos_efectivos", models.PositiveIntegerField(default=0)),
                ("fecha_salida", models.DateField(db_index=True)),
                (
                    "fecha_retorno_esp",
                    models.DateField(
                        db_index=True, verbose_name="fecha retorno esperada"
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("confirmada", "Confirmada"),
                            ("planeada", "Planeada"),
                        ],
                        default="confirmada",
                        max_length=12,
                    ),
                ),
                ("cancelada", models.BooleanField(db_index=True, default=False)),
                ("motivo_cancelacion", models.TextField(blank=True)),
                ("reprogramada_desde", models.DateField(blank=True, null=True)),
                ("riesgo", models.FloatField(default=0.0)),
                ("creada_en", models.DateTimeField(auto_now_add=True)),
                (
                    "ciudad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reservas",
                        to="catalogo.ciudad",
                    ),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reservas",
                        to="catalogo.empresa",
                    ),
                ),
                (
                    "equipos",
                    models.ManyToManyField(
                        blank=True, related_name="reservas", to="equipos.equipo"
                    ),
                ),
                (
                    "paquete",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reservas",
                        to="paquetes.paquete",
                    ),
                ),
                (
                    "servicio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reservas",
                        to="catalogo.servicio",
                    ),
                ),
                (
                    "solicitud",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reservas",
                        to="solicitudes.solicitud",
                    ),
                ),
            ],
            options={
                "verbose_name": "reserva",
                "verbose_name_plural": "reservas",
                "ordering": ["-fecha_salida"],
            },
        ),
        migrations.CreateModel(
            name="HistorialReserva",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("accion", models.CharField(max_length=40)),
                ("detalle", models.TextField(blank=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="acciones_reserva",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reserva",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historial",
                        to="reservas.reserva",
                    ),
                ),
            ],
            options={
                "verbose_name": "historial de reserva",
                "verbose_name_plural": "historial de reservas",
                "ordering": ["timestamp"],
            },
        ),
        migrations.CreateModel(
            name="ConfirmacionRetorno",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField()),
                (
                    "estado_kit",
                    models.CharField(
                        choices=[
                            ("OK", "OK"),
                            ("INCOMPLETO", "Incompleto"),
                            ("DAÑADO", "Dañado"),
                        ],
                        default="OK",
                        max_length=12,
                    ),
                ),
                ("notas", models.TextField(blank=True)),
                ("requiere_preparacion", models.BooleanField(default=False)),
                ("preparacion_completa", models.BooleanField(default=False)),
                ("preparacion_notas", models.TextField(blank=True)),
                (
                    "operador",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="retornos_confirmados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reserva",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="confirmacion_retorno",
                        to="reservas.reserva",
                    ),
                ),
            ],
            options={
                "verbose_name": "confirmación de retorno",
                "verbose_name_plural": "confirmaciones de retorno",
            },
        ),
    ]
