# Generated by Django 6.0.7 on 2026-07-13 20:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfiguracionCanal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "canal",
                    models.CharField(
                        choices=[
                            ("whatsapp", "WhatsApp Business"),
                            ("email", "Correo logística"),
                            ("teams", "Microsoft Teams"),
                        ],
                        max_length=12,
                        unique=True,
                    ),
                ),
                ("activo", models.BooleanField(default=False)),
                ("label", models.CharField(blank=True, max_length=60)),
                (
                    "destino",
                    models.CharField(
                        blank=True,
                        help_text="Número de teléfono, correo o nombre del canal Teams",
                        max_length=200,
                    ),
                ),
            ],
            options={
                "verbose_name": "configuración de canal",
                "verbose_name_plural": "configuración de canales",
                "ordering": ["canal"],
            },
        ),
        migrations.CreateModel(
            name="AlertaEnviada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tipo", models.CharField(max_length=30)),
                (
                    "canal",
                    models.CharField(
                        choices=[
                            ("whatsapp", "WhatsApp Business"),
                            ("email", "Correo logística"),
                            ("teams", "Microsoft Teams"),
                        ],
                        max_length=12,
                    ),
                ),
                ("mensaje", models.TextField()),
                ("destino", models.CharField(blank=True, max_length=200)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("resultado", models.CharField(blank=True, max_length=200)),
                (
                    "enviada_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="alertas_enviadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "alerta enviada",
                "verbose_name_plural": "alertas enviadas",
                "ordering": ["-timestamp"],
            },
        ),
    ]
