# Generated by Django 6.0.7 on 2026-07-13 20:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalogo", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Solicitud",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        blank=True, max_length=20, unique=True, verbose_name="código"
                    ),
                ),
                ("personas", models.PositiveIntegerField()),
                ("fecha_solicitud", models.DateField(auto_now_add=True)),
                ("fecha_sugerida", models.DateField()),
                ("dias_estimados", models.PositiveIntegerField(default=1)),
                ("fecha_confirmada", models.DateField(blank=True, null=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("confirmada", "Confirmada"),
                            ("finalizada", "Finalizada"),
                            ("cancelada", "Cancelada"),
                        ],
                        db_index=True,
                        default="pendiente",
                        max_length=12,
                    ),
                ),
                ("notas", models.TextField(blank=True)),
                (
                    "prof_cantidad",
                    models.PositiveIntegerField(
                        default=1, verbose_name="profesionales requeridos"
                    ),
                ),
                (
                    "prof_perfil",
                    models.CharField(
                        max_length=120, verbose_name="perfil del profesional"
                    ),
                ),
                (
                    "prof_nombre",
                    models.CharField(
                        blank=True,
                        max_length=120,
                        verbose_name="nombre del profesional",
                    ),
                ),
                ("prof_especialidad", models.CharField(blank=True, max_length=120)),
                ("prof_telefono", models.CharField(blank=True, max_length=30)),
                ("prof_correo", models.EmailField(blank=True, max_length=254)),
                ("motivo_cancelacion", models.TextField(blank=True)),
                ("fecha_cancelacion", models.DateField(blank=True, null=True)),
                ("editada", models.BooleanField(default=False)),
                ("notificada_a", models.JSONField(blank=True, default=list)),
                ("notificada_en", models.DateTimeField(blank=True, null=True)),
                ("creada_en", models.DateTimeField(auto_now_add=True)),
                (
                    "cancelada_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="solicitudes_canceladas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ciudad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="solicitudes",
                        to="catalogo.ciudad",
                    ),
                ),
                (
                    "editada_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="solicitudes_editadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "empresa_cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="solicitudes",
                        to="catalogo.empresa",
                    ),
                ),
                (
                    "operador",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="solicitudes_atendidas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "servicio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="solicitudes",
                        to="catalogo.servicio",
                    ),
                ),
                (
                    "solicitante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="solicitudes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "solicitud",
                "verbose_name_plural": "solicitudes",
                "ordering": ["-creada_en"],
            },
        ),
        migrations.CreateModel(
            name="Observacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                ("texto", models.TextField()),
                (
                    "autor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="observaciones_solicitud",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "solicitud",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="observaciones",
                        to="solicitudes.solicitud",
                    ),
                ),
            ],
            options={
                "verbose_name": "observación",
                "verbose_name_plural": "observaciones",
                "ordering": ["fecha"],
            },
        ),
        migrations.CreateModel(
            name="AccesorioSolicitado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=120)),
                ("cantidad", models.PositiveIntegerField(default=1)),
                (
                    "solicitud",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accesorios_solicitados",
                        to="solicitudes.solicitud",
                    ),
                ),
            ],
            options={
                "verbose_name": "accesorio solicitado",
                "verbose_name_plural": "accesorios solicitados",
                "ordering": ["id"],
            },
        ),
    ]
