# Generated by Django 6.0.7 on 2026-07-13 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalogo", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Equipo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(max_length=20, unique=True, verbose_name="código"),
                ),
                ("modelo", models.CharField(max_length=120)),
                ("serial", models.CharField(max_length=60, unique=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("disponible", "Disponible"),
                            ("en_uso", "En uso"),
                            ("en_preparacion", "En preparación"),
                            ("en_revision", "En revisión"),
                            ("en_mantenimiento", "En mantenimiento"),
                            ("en_transito", "En tránsito"),
                            ("de_baja", "De baja"),
                        ],
                        db_index=True,
                        default="disponible",
                        max_length=20,
                    ),
                ),
                ("responsable", models.CharField(blank=True, max_length=120)),
                ("ultima_revision", models.DateField(blank=True, null=True)),
                ("proxima_mantencion", models.DateField(blank=True, null=True)),
                ("notas", models.TextField(blank=True)),
                ("historial_uso", models.PositiveIntegerField(default=0)),
                ("motivo_mantenimiento", models.TextField(blank=True)),
                ("motivo_baja", models.TextField(blank=True)),
                ("fecha_baja", models.DateField(blank=True, null=True)),
                (
                    "ciudad_base",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="equipos",
                        to="catalogo.ciudad",
                    ),
                ),
                (
                    "servicio",
                    models.ForeignKey(
                        help_text="Categoría del equipo (Xsens, EMG, …)",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="equipos",
                        to="catalogo.servicio",
                    ),
                ),
            ],
            options={
                "verbose_name": "equipo",
                "verbose_name_plural": "equipos",
                "ordering": ["codigo"],
            },
        ),
        migrations.CreateModel(
            name="Accesorio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=120)),
                ("cantidad", models.PositiveIntegerField(default=1)),
                ("completo", models.BooleanField(default=True)),
                ("requiere_lavado", models.BooleanField(default=False)),
                ("consumible", models.BooleanField(default=False)),
                (
                    "equipo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accesorios",
                        to="equipos.equipo",
                    ),
                ),
            ],
            options={
                "verbose_name": "accesorio",
                "verbose_name_plural": "accesorios",
                "ordering": ["id"],
            },
        ),
    ]
