#!/usr/bin/env bash

### Create a database backup.
###
### Usage:
###     $ docker compose -f docker-compose.local.yml exec postgres backup

set -o errexit
set -o pipefail
set -o nounset

BACKUP_DIR_PATH='/backups'
BACKUP_FILE_PREFIX='backup'

export PGHOST="${POSTGRES_HOST:-localhost}"
export PGPORT="${POSTGRES_PORT:-5432}"
export PGUSER="${POSTGRES_USER}"
export PGPASSWORD="${POSTGRES_PASSWORD}"
export PGDATABASE="${POSTGRES_DB}"

backup_filename="${BACKUP_FILE_PREFIX}_$(date +'%Y_%m_%dT%H_%M_%S').sql.gz"
pg_dump | gzip > "${BACKUP_DIR_PATH}/${backup_filename}"

echo "Backup '${backup_filename}' created."
