#!/usr/bin/env bash

### Restore database from a backup.
###
### Parameters:
###     <1> filename of an existing backup.
###
### Usage:
###     $ docker compose -f docker-compose.local.yml exec postgres restore <1>

set -o errexit
set -o pipefail
set -o nounset

BACKUP_DIR_PATH='/backups'

if [[ -z ${1+x} ]]; then
    echo "Backup filename is not specified." >&2
    exit 1
fi
backup_filename="${BACKUP_DIR_PATH}/${1}"
if [[ ! -f "${backup_filename}" ]]; then
    echo "No backup with the specified filename found." >&2
    exit 1
fi

export PGHOST="${POSTGRES_HOST:-localhost}"
export PGPORT="${POSTGRES_PORT:-5432}"
export PGUSER="${POSTGRES_USER}"
export PGPASSWORD="${POSTGRES_PASSWORD}"
export PGDATABASE="${POSTGRES_DB}"

echo "Dropping the database..."
dropdb "${PGDATABASE}"
echo "Creating a new database..."
createdb --owner="${POSTGRES_USER}"
echo "Applying the backup to the new database..."
gunzip -c "${backup_filename}" | psql "${POSTGRES_DB}"

echo "Backup applied."
