# Generated by Django 6.0.7 on 2026-07-13 20:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PrediccionRegistro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("servicio", models.CharField(max_length=60)),
                ("ciudad", models.CharField(max_length=80)),
                ("cliente", models.CharField(max_length=120)),
                ("personas", models.PositiveIntegerField()),
                ("sector", models.CharField(blank=True, max_length=80)),
                ("jornada", models.CharField(blank=True, max_length=80)),
                ("score", models.FloatField()),
                ("modelo_version", models.CharField(max_length=40)),
                ("es_simulacion", models.BooleanField(default=True)),
                ("factores", models.JSONField(blank=True, default=list)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="predicciones",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "registro de predicción",
                "verbose_name_plural": "registros de predicción",
                "ordering": ["-creado_en"],
            },
        ),
    ]
