# Generated by Django 6.0.7 on 2026-07-15 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("predictivo", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="prediccionregistro",
            name="zonas",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
