# Generated by Django 6.0.7 on 2026-07-13 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        blank=True, max_length=20, unique=True, verbose_name="código"
                    ),
                ),
                ("area", models.CharField(max_length=60, verbose_name="área")),
                ("titulo", models.CharField(max_length=200)),
                ("descripcion", models.TextField(blank=True)),
                ("responsable", models.CharField(max_length=120)),
                ("vence", models.DateField()),
                (
                    "avance",
                    models.PositiveIntegerField(
                        default=0, help_text="Porcentaje 0-100"
                    ),
                ),
                (
                    "esperado",
                    models.PositiveIntegerField(
                        default=0, help_text="Porcentaje esperado a hoy"
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("open", "Abierto"),
                            ("risk", "En riesgo"),
                            ("done", "Completado"),
                        ],
                        db_index=True,
                        default="open",
                        max_length=8,
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "plan de acción",
                "verbose_name_plural": "planes de acción",
                "ordering": ["vence"],
            },
        ),
    ]
