# Generated by Django 6.0.7 on 2026-07-13 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogo", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="empresa",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="usuarios",
                to="catalogo.empresa",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="modulos_permitidos",
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="nivel",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "Admin Global"),
                    (2, "Operador"),
                    (3, "Coordinador Programación"),
                    (4, "Solicitante"),
                ],
                db_index=True,
                default=4,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="permisos_extra",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="user",
            name="rol_descriptivo",
            field=models.CharField(
                blank=True,
                help_text="Cargo visible, p.ej. 'Coordinadora General'",
                max_length=120,
            ),
        ),
    ]
