# Generated by Django 6.0.7 on 2026-07-13 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalogo", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Paquete",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(max_length=20, unique=True, verbose_name="código"),
                ),
                ("nombre", models.CharField(max_length=120)),
                ("descripcion", models.TextField(blank=True)),
                ("duracion_dias", models.PositiveIntegerField(default=1)),
                ("activo", models.BooleanField(default=True)),
                (
                    "servicios_requeridos",
                    models.ManyToManyField(
                        related_name="paquetes", to="catalogo.servicio"
                    ),
                ),
            ],
            options={
                "verbose_name": "paquete",
                "verbose_name_plural": "paquetes",
                "ordering": ["codigo"],
            },
        ),
    ]
