# Generated by Django 6.0.7 on 2026-07-13 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ciudad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=80, unique=True)),
            ],
            options={
                "verbose_name": "ciudad",
                "verbose_name_plural": "ciudades",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Empresa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=120, unique=True)),
                ("sector", models.CharField(blank=True, max_length=80)),
            ],
            options={
                "verbose_name": "empresa",
                "verbose_name_plural": "empresas",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Servicio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=60, unique=True)),
                ("descripcion", models.TextField(blank=True)),
                ("requiere_equipo_fisico", models.BooleanField(default=True)),
                ("activo", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "servicio",
                "verbose_name_plural": "servicios",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="AccesorioTipo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=120)),
                ("cantidad_default", models.PositiveIntegerField(default=1)),
                (
                    "servicio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accesorios_tipicos",
                        to="catalogo.servicio",
                    ),
                ),
            ],
            options={
                "verbose_name": "accesorio típico",
                "verbose_name_plural": "accesorios típicos",
                "ordering": ["servicio", "nombre"],
                "unique_together": {("servicio", "nombre")},
            },
        ),
    ]
